//
// Created by Moch Xiao on 12/7/15.
//

#ifndef MASTERINGALGORITHMS_LINKEDLIST_TEST_H
#define MASTERINGALGORITHMS_LINKEDLIST_TEST_H

void test_linkedlist();

#endif //MASTERINGALGORITHMS_LINKEDLIST_TEST_H
